2022-11-18 13:58:32,673-INFO-Token Request : g9OOtxUteYy7gDr - {'subscriberid': '94332295601', 'packageId': 8, 'type': 'ADDON_CREATE', 'userID': 'OCS_PCRF'}
2022-11-18 13:58:53,822-INFO-Token Response : g9OOtxUteYy7gDr - {'result': 'error', 'msg': ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.25.16.215', port=8085): Max retries exceeded with url: /subscribertoken (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002411D9EC550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"))}
2022-11-18 13:58:53,823-ERROR-Return : g9OOtxUteYy7gDr - {'result': 'error', 'msg': 'Connection Issue'}
2022-11-22 13:54:33,103-INFO-Token Request : LcZl0zdCqi3mec6 - {'subscriberid': '94332295601', 'packageId': 8, 'type': 'ADDON_CREATE', 'userID': 'OCS_PCRF'}
2022-11-22 13:54:54,232-INFO-Token Response : LcZl0zdCqi3mec6 - {'result': 'error', 'msg': ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.25.16.215', port=8085): Max retries exceeded with url: /subscribertoken (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D8A037A550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"))}
2022-11-22 13:54:54,233-ERROR-Return : LcZl0zdCqi3mec6 - {'result': 'error', 'msg': 'Connection Issue'}
2022-11-22 14:01:48,980-INFO-Token Request : o8s1yD4oj4Q6Vj4 - {'subscriberid': '94332295601', 'packageId': 8, 'type': 'ADDON_CREATE', 'userID': 'OCS_PCRF'}
2022-11-22 14:02:10,035-INFO-Token Response : o8s1yD4oj4Q6Vj4 - {'result': 'error', 'msg': ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.25.16.215', port=8085): Max retries exceeded with url: /subscribertoken (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B364A08E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"))}
2022-11-22 14:02:10,036-ERROR-Return : o8s1yD4oj4Q6Vj4 - {'result': 'error', 'msg': 'Connection Issue'}
2022-11-22 14:18:58,369-INFO-Token Request : m6VhQgfSRlOzQK0 - {'subscriberid': '94332295601', 'packageId': 8, 'type': 'ADDON_CREATE', 'userID': 'OCS_PCRF'}
2022-11-22 14:19:19,445-INFO-Token Response : m6VhQgfSRlOzQK0 - {'result': 'error', 'msg': ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.25.16.215', port=8085): Max retries exceeded with url: /subscribertoken (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E438658D00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"))}
2022-11-22 14:19:19,446-ERROR-Return : m6VhQgfSRlOzQK0 - {'result': 'error', 'msg': 'Connection Issue'}
